<a href="https://colab.research.google.com/github/jungeun919/Deep_learning/blob/main/Predict_Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 아이리스 품종 분류


In [1]:
import tensorflow as tf
import pandas as pd

In [2]:
# 과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [3]:
# 원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [4]:
# 칼럼이름 출력
print(인코딩.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [5]:
# 독립변수, 종속변수
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [6]:
# 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [7]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 2s 3ms/step - loss: 3.4347 - accuracy: 0.3433
Epoch 2/100
5/5 [==============================] - 0s 3ms/step - loss: 3.3027 - accuracy: 0.3381
Epoch 3/100
5/5 [==============================] - 0s 3ms/step - loss: 3.2994 - accuracy: 0.3155
Epoch 4/100
5/5 [==============================] - 0s 3ms/step - loss: 3.0865 - accuracy: 0.3529
Epoch 5/100
5/5 [==============================] - 0s 3ms/step - loss: 3.0174 - accuracy: 0.3464
Epoch 6/100
5/5 [==============================] - 0s 2ms/step - loss: 2.9021 - accuracy: 0.3199
Epoch 7/100
5/5 [==============================] - 0s 2ms/step - loss: 2.7940 - accuracy: 0.3828
Epoch 8/100
5/5 [==============================] - 0s 3ms/step - loss: 3.0965 - accuracy: 0.3134
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 2.8003 - accuracy: 0.2951
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 2.5435 - accuracy: 0.3681
Epoch 11/100
5/5 [===========

In [8]:
# 모델을 이용합니다. 
print(model.predict(독립[:5]))
print(종속[:5])

print(model.predict(독립[-5:]))
print(종속[-5:])


[[0.7168888  0.09093291 0.19217831]
 [0.5984407  0.13708216 0.26447713]
 [0.68790454 0.10783651 0.20425898]
 [0.66674274 0.12769012 0.20556715]
 [0.75393236 0.0811497  0.16491795]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
[[0.06432228 0.34936467 0.586313  ]
 [0.05783178 0.4246042  0.51756406]
 [0.08683503 0.40297082 0.5101942 ]
 [0.12981448 0.39164844 0.4785371 ]
 [0.13260525 0.45174995 0.41564474]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [9]:
# weights & bias 출력
print(model.get_weights())

[array([[-0.69713914, -0.36857918,  0.04123674],
       [ 0.7897909 , -0.5237367 , -0.505409  ],
       [ 0.25414592,  0.7628403 ,  0.16388346],
       [-0.08121587,  0.2242655 ,  0.8904228 ]], dtype=float32), array([ 0.23295122,  0.316575  , -0.3840236 ], dtype=float32)]
