<a href="https://colab.research.google.com/github/jungeun919/Deep_learning/blob/main/Use_Multi_layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 히든레이어 사용하기

In [1]:
import tensorflow as tf
import pandas as pd

# 보스턴 집값 예측

In [2]:
# 과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)

# 종속변수, 독립변수
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [3]:
# 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [4]:
# 모델 구조 확인
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                140       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [5]:
# 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=100)

Epoch 1/100
16/16 [==============================] - 2s 2ms/step - loss: 65572.4306
Epoch 2/100
16/16 [==============================] - 0s 2ms/step - loss: 42341.7273
Epoch 3/100
16/16 [==============================] - 0s 2ms/step - loss: 28362.5628
Epoch 4/100
16/16 [==============================] - 0s 2ms/step - loss: 18014.2702
Epoch 5/100
16/16 [==============================] - 0s 2ms/step - loss: 9473.8152
Epoch 6/100
16/16 [==============================] - 0s 2ms/step - loss: 4269.0855
Epoch 7/100
16/16 [==============================] - 0s 2ms/step - loss: 1295.7177
Epoch 8/100
16/16 [==============================] - 0s 2ms/step - loss: 486.6590
Epoch 9/100
16/16 [==============================] - 0s 2ms/step - loss: 384.9922
Epoch 10/100
16/16 [==============================] - 0s 3ms/step - loss: 321.1090
Epoch 11/100
16/16 [==============================] - 0s 2ms/step - loss: 256.3957
Epoch 12/100
16/16 [==============================] - 0s 2ms/step - loss: 214.6164
Ep

In [6]:
# 모델을 이용합니다
print(model.predict(독립[:5]))
print(종속[:5])

[[26.805895]
 [24.169666]
 [28.320663]
 [29.998419]
 [28.62973 ]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


# 아이리스 품종 분류


In [7]:
# 과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)

# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [8]:
# 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [9]:
# 모델 구조 확인
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_3 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [10]:
# 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 3ms/step - loss: 1.2980 - accuracy: 0.3815
Epoch 2/100
5/5 [==============================] - 0s 3ms/step - loss: 1.1766 - accuracy: 0.3780
Epoch 3/100
5/5 [==============================] - 0s 3ms/step - loss: 1.1712 - accuracy: 0.3112
Epoch 4/100
5/5 [==============================] - 0s 3ms/step - loss: 1.1047 - accuracy: 0.3737
Epoch 5/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0674 - accuracy: 0.3429
Epoch 6/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0497 - accuracy: 0.3440
Epoch 7/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0052 - accuracy: 0.5377
Epoch 8/100
5/5 [==============================] - 0s 3ms/step - loss: 0.9774 - accuracy: 0.6342
Epoch 9/100
5/5 [==============================] - 0s 3ms/step - loss: 0.9443 - accuracy: 0.5904
Epoch 10/100
5/5 [==============================] - 0s 4ms/step - loss: 0.9090 - accuracy: 0.5787
Epoch 11/100
5/5 [===========

In [11]:
# 모델을 이용합니다
print(model.predict(독립[0:5]))
print(종속[0:5])

[[9.98841584e-01 1.15837483e-03 9.23073173e-08]
 [9.98281598e-01 1.71821087e-03 1.99252824e-07]
 [9.98384118e-01 1.61563081e-03 2.59163301e-07]
 [9.97506917e-01 2.49258871e-03 5.11975202e-07]
 [9.98779833e-01 1.22007553e-03 1.16342825e-07]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
